using System;
using System.Collections.Generic;
using System.Windows;

namespace Hafiza.Services;

public static class LocalizationService
{
    public const string English = "en";
    public const string Arabic = "ar";

    public static string CurrentLanguage { get; set; } = English;

    public static bool IsArabic => string.Equals(CurrentLanguage, Arabic, StringComparison.OrdinalIgnoreCase);

    public static FlowDirection CurrentFlowDirection =>
        IsArabic ? FlowDirection.RightToLeft : FlowDirection.LeftToRight;

    public static void ApplyLanguage(string? language, ResourceDictionary? resources = null)
    {
        CurrentLanguage = string.Equals(language, Arabic, StringComparison.OrdinalIgnoreCase) ? Arabic : English;
        var dict = IsArabic ? ArabicStrings : EnglishStrings;
        var target = resources ?? Application.Current?.Resources;
        if (target != null)
        {
            foreach (var kvp in dict)
            {
                target["Loc_" + kvp.Key] = kvp.Value;
            }
        }
    }

    private static readonly Dictionary<string, string> EnglishStrings = new(StringComparer.Ordinal)
    {
        ["AppTitle"] = "Hafiza",
        ["AppSubtitle"] = "Everything you copied, in one place",
        ["TooltipSettings"] = "Settings",
        ["TooltipKeepOpen"] = "Keep window open after paste",
        ["TooltipThemeDark"] = "Switch to Light Mode",
        ["TooltipThemeLight"] = "Switch to Dark Mode",
        ["TooltipLanguage"] = "التبديل إلى العربية",
        ["TooltipUndo"] = "Undo last delete",
        ["TooltipSelection"] = "Select multiple items",
        ["TooltipPause"] = "Pause capture",
        ["TooltipResume"] = "Resume capture",
        ["TooltipHide"] = "Hide",
        ["AllTab"] = "All",
        ["TooltipNewTab"] = "New tab",
        ["TooltipTabActions"] = "Right-click to rename or delete",
        ["SearchTooltip"] = "Search clipboard history",
        ["SearchHint"] = "Search clipboard…",
        ["SearchClearTooltip"] = "Clear search",
        ["TooltipNewFolder"] = "New folder",
        ["TooltipFolderBack"] = "Back to tab",
        ["TooltipFolderOptions"] = "Folder options",
        ["EmptyTitle"] = "Clipboard is waiting for your first copy",
        ["EmptySubtitle"] = "Copy text or images and they will appear here automatically",
        ["EmptySearchTitle"] = "No matching clips",
        ["EmptySearchSubtitle"] = "Try searching with different keywords",
        ["ClearUnpinned"] = "Clear unpinned",
        ["StatusActive"] = "Capture active",
        ["StatusPaused"] = "Capture paused",
        ["BulkMove"] = "Move",
        ["ErrorButton"] = "View issue",
        ["CardPin"] = "Pin in current tab",
        ["CardUnpin"] = "Unpin from current tab",
        ["CardDelete"] = "Delete from current tab",
        ["CardMore"] = "More options",
        ["CardDrag"] = "Drag up or down to reorder",
        ["CardSelect"] = "Select item",
        ["CardCopy"] = "Copy item or selected items",
        ["CardReturnToTab"] = "Return to tab outside folder",
        ["ImageClick"] = "Click to paste image",
        ["ImageMissing"] = "Original image unavailable",
        ["FolderPin"] = "Pin folder",
        ["FolderDelete"] = "Delete folder",
        ["FolderCopy"] = "Copy folder contents",
        ["FolderDrag"] = "Drag to reorder folder",
        ["FolderPill"] = "Open folder or drop cards here",
        ["FolderExpand"] = "Expand or collapse folder",
        ["FolderOptions"] = "Folder options",
        ["MenuAddToTab"] = "Add to tab",
        ["MenuCopy"] = "Copy",
        ["MenuPastePlainText"] = "Paste as plain text",
        ["MenuShowImagePreview"] = "Enlarge image",
        ["MenuSetShortcut"] = "Set paste shortcut",
        ["MenuShortcutFormat"] = "Paste shortcut: {0}",
        ["MenuMoveToFolder"] = "Move to folder",
        ["MenuMoveSelectedToFolder"] = "Move selected to folder",
        ["MenuOutsideFolders"] = "Outside folders",
        ["MenuNewFolderEllipsis"] = "New folder…",
        ["MenuRenameCard"] = "Rename item",
        ["MenuRenameSelectedCards"] = "Rename selected items",
        ["MenuMoveToTop"] = "Move to top ⤒",
        ["MenuMoveToBottom"] = "Move to bottom ⤓",
        ["MenuNoTabsYet"] = "No tabs yet",
        ["MenuDeleteCard"] = "Delete",
        ["StatusMovedToTop"] = "Item moved to top of tab",
        ["StatusMovedToTopPlural"] = "Items moved to top of tab",
        ["StatusMovedToBottom"] = "Item moved to bottom of tab",
        ["StatusMovedToBottomPlural"] = "Items moved to bottom of tab",
        ["StatusMovedToFolderTop"] = "Item moved to top of folder",
        ["StatusMovedToFolderTopPlural"] = "Items moved to top of folder",
        ["StatusMovedToFolderBottom"] = "Item moved to bottom of folder",
        ["StatusMovedToFolderBottomPlural"] = "Items moved to bottom of folder",
        ["StatusCopied"] = "Copied",
        ["StatusPasted"] = "Pasted",
        ["StatusCopiedMultiple"] = "Copied {0} items together",
        ["StatusFolderEmpty"] = "Folder is empty",
        ["StatusMovedToFolder"] = "Moved to {0}",
        ["StatusMovedToFolderPlural"] = "Moved {0} items to {1}",
        ["StatusShortcutRemoved"] = "Paste shortcut removed",
        ["StatusShortcutSaved"] = "Paste shortcut saved",
        ["StatusShortcutConflict"] = "Shortcut already in use; not changed",
        ["MenuRenameFolder"] = "Rename folder",
        ["MenuMoveFolderToTab"] = "Move folder to tab",
        ["MenuMoveFolderUp"] = "Move up ▲",
        ["MenuMoveFolderDown"] = "Move down ▼",
        ["MenuMoveFolderToTop"] = "Move to top ⤒",
        ["MenuMoveFolderToBottom"] = "Move to bottom ⤓",
        ["MenuDeleteFolder"] = "Delete folder…",
        ["DeleteFolderConfirm"] = "Delete folder «{0}»? Items will be kept in the tab.",
        ["DeleteTabConfirm"] = "Delete tab «{0}»? Items will be moved to «All».",
        ["TrayOpen"] = "Open Hafiza",
        ["TrayPauseResume"] = "Pause/Resume capture",
        ["TrayExit"] = "Exit",
        ["SettingsTitle"] = "Hafiza Settings",
        ["SettingsMaxEntries"] = "Maximum entries",
        ["SettingsCardDensity"] = "Card density",
        ["DensityCompact"] = "Compact",
        ["DensityMedium"] = "Medium",
        ["DensityLarge"] = "Large",
        ["SettingsWindowPosition"] = "Window position",
        ["PositionBottomRight"] = "Bottom right",
        ["PositionBottomLeft"] = "Bottom left",
        ["PositionCenter"] = "Center screen",
        ["SettingsTheme"] = "Appearance",
        ["ThemeDark"] = "Dark",
        ["ThemeLight"] = "Light",
        ["SettingsLanguage"] = "Language",
        ["LangEnglish"] = "English",
        ["LangArabic"] = "العربية (Arabic)",
        ["SettingsHotkey"] = "Open hotkey",
        ["SettingsHotkeyTooltip"] = "Click here and press the desired shortcut",
        ["SettingsAnimations"] = "Enable appearance animation",
        ["SettingsStartup"] = "Start Hafiza with Windows",
        ["SettingsBootCleanup"] = "Clean All tab after Windows restart",
        ["SettingsBootCleanupTip"] = "The All tab is temporary, while custom tabs are permanently kept.",
        ["SettingsBootCleanupHint"] = "Clears everything in «All» upon a new Windows session, while keeping all custom tab items intact.",
        ["SettingsExport"] = "Export backup",
        ["SettingsImport"] = "Restore backup",
        ["SettingsSave"] = "Save settings",
        ["DialogTabNameTitle"] = "Tab Name",
        ["DialogFolderNameTitle"] = "Folder Name",
        ["DialogCardNameTitle"] = "Item Name",
        ["DialogSave"] = "Save",
        ["DialogCancel"] = "Cancel",
        ["DialogRemoveShortcut"] = "Remove Shortcut",
        ["DialogHotkeyTitle"] = "Paste Shortcut",
        ["DialogHotkeyInstructions"] = "Press shortcut keys (e.g. Ctrl + Shift + 1)",
        ["ImagePreviewTitle"] = "Image Preview",
        ["StatusFolderMoved"] = "Folder moved with {0} items",
        ["StatusFolderDropHint"] = "Drop folder «{0}» to change position",
        ["StatusFolderContentsCopied"] = "Copied contents of {0}",
        ["StatusCopiedSelected"] = "Copied selected items",
        ["DeleteFolderPrompt"] = "Yes: Delete folder and keep items in tab.\nNo: Delete folder and its items from this tab only.",
        ["DeleteFolderTitle"] = "Delete Folder",
        ["DeleteConfirmTitle"] = "Confirm",
        ["DeleteCardsCountPrompt"] = "Delete {0} cards from this tab?",
        ["DeleteBatchConfirm"] = "Delete {0} items from current tab? You can undo after deletion.",
        ["DeleteBatchTitle"] = "Confirm Delete",
        ["TooltipUndoWithCount"] = "Undo last delete — {0} operation(s) available",
        ["TooltipKeepOpenPinned"] = "Pinned: window will remain open after paste",
        ["SettingsBackupFilter"] = "Full Hafiza Backup|*.hafiza",
        ["SettingsRestoreFilter"] = "Full Hafiza Backup|*.hafiza|Legacy Backup|*.json",
        ["SettingsNoticeShortcutCaptured"] = "Shortcut captured. Click Save Settings.",
        ["SettingsNoticeExportSuccess"] = "Backup exported successfully.",
        ["SettingsNoticeExportFailed"] = "Could not export backup. See issue button.",
        ["SettingsNoticeImportFailed"] = "Invalid backup or could not restore.",
        ["SettingsNoticeModifierOnly"] = "Use Ctrl, Alt, or Shift with the key.",
        ["MoreTabsTooltip"] = "More tabs",
    };

    private static readonly Dictionary<string, string> ArabicStrings = new(StringComparer.Ordinal)
    {
        ["AppTitle"] = "حافظة",
        ["AppSubtitle"] = "كل ما نسخته، في مكانه",
        ["TooltipSettings"] = "الإعدادات",
        ["TooltipKeepOpen"] = "إبقاء النافذة ظاهرة بعد اللصق",
        ["TooltipThemeDark"] = "الوضع النهاري",
        ["TooltipThemeLight"] = "الوضع الليلي",
        ["TooltipLanguage"] = "Switch to English",
        ["TooltipUndo"] = "تراجع عن آخر حذف",
        ["TooltipSelection"] = "تحديد عدة عناصر",
        ["TooltipPause"] = "إيقاف الالتقاط مؤقتًا",
        ["TooltipResume"] = "استئناف الالتقاط",
        ["TooltipHide"] = "إخفاء",
        ["AllTab"] = "الكل",
        ["TooltipNewTab"] = "تبويب جديد",
        ["TooltipTabActions"] = "زر أيمن لإعادة التسمية أو الحذف",
        ["SearchTooltip"] = "ابحث في النصوص المحفوظة",
        ["SearchHint"] = "ابحث في الحافظة…",
        ["SearchClearTooltip"] = "مسح البحث",
        ["TooltipNewFolder"] = "فولدر جديد",
        ["TooltipFolderBack"] = "الرجوع إلى التبويب",
        ["TooltipFolderOptions"] = "خيارات الفولدر",
        ["EmptyTitle"] = "الحافظة تنتظر أول نسخة",
        ["EmptySubtitle"] = "انسخ نصًا أو صورة وستظهر هنا تلقائيًا",
        ["EmptySearchTitle"] = "لا توجد عناصر مطابقة",
        ["EmptySearchSubtitle"] = "جرّب البحث بكلمات أخرى",
        ["ClearUnpinned"] = "مسح غير المثبّت",
        ["StatusActive"] = "الالتقاط يعمل",
        ["StatusPaused"] = "الالتقاط متوقف",
        ["BulkMove"] = "نقل",
        ["ErrorButton"] = "عرض المشكلة",
        ["CardPin"] = "تثبيت داخل التبويب الحالي",
        ["CardUnpin"] = "إلغاء التثبيت من التبويب الحالي",
        ["CardDelete"] = "حذف من التبويب الحالي",
        ["CardMore"] = "المزيد",
        ["CardDrag"] = "اسحب لأعلى أو لأسفل لإعادة ترتيب البطاقة",
        ["CardSelect"] = "تحديد البطاقة",
        ["CardCopy"] = "نسخ البطاقة أو البطاقات المحددة",
        ["CardReturnToTab"] = "إرجاع إلى التبويب خارج الفولدر",
        ["ImageClick"] = "اضغط للصق الصورة",
        ["ImageMissing"] = "الصورة الأصلية غير متاحة",
        ["FolderPin"] = "تثبيت الفولدر",
        ["FolderDelete"] = "حذف الفولدر",
        ["FolderCopy"] = "نسخ محتويات الفولدر",
        ["FolderDrag"] = "اسحب لتغيير ترتيب الفولدر في القائمة",
        ["FolderPill"] = "افتح الفولدر أو أفلت البطاقات فوقه",
        ["FolderExpand"] = "عرض أو طي محتويات الفولدر",
        ["FolderOptions"] = "خيارات الفولدر",
        ["MenuAddToTab"] = "إضافة إلى تبويب",
        ["MenuCopy"] = "نسخ",
        ["MenuPastePlainText"] = "لصق كنص عادي",
        ["MenuShowImagePreview"] = "تكبير الصورة",
        ["MenuSetShortcut"] = "تعيين اختصار للصق",
        ["MenuShortcutFormat"] = "اختصار اللصق: {0}",
        ["MenuMoveToFolder"] = "نقل إلى فولدر",
        ["MenuMoveSelectedToFolder"] = "نقل العناصر إلى فولدر",
        ["MenuOutsideFolders"] = "خارج الفولدرات",
        ["MenuNewFolderEllipsis"] = "فولدر جديد…",
        ["MenuRenameCard"] = "تسمية العنصر",
        ["MenuRenameSelectedCards"] = "تسمية العناصر المحددة",
        ["MenuMoveToTop"] = "تحريك لأعلى ⤒",
        ["MenuMoveToBottom"] = "تحريك لأسفل ⤓",
        ["MenuNoTabsYet"] = "لا توجد تبويبات بعد",
        ["MenuDeleteCard"] = "حذف",
        ["StatusMovedToTop"] = "تم نقل البطاقة إلى أول التبويب",
        ["StatusMovedToTopPlural"] = "تم نقل العناصر إلى أول التبويب",
        ["StatusMovedToBottom"] = "تم نقل البطاقة إلى آخر التبويب",
        ["StatusMovedToBottomPlural"] = "تم نقل العناصر إلى آخر التبويب",
        ["StatusMovedToFolderTop"] = "تم نقل البطاقة إلى أول الفولدر",
        ["StatusMovedToFolderTopPlural"] = "تم نقل العناصر إلى أول الفولدر",
        ["StatusMovedToFolderBottom"] = "تم نقل البطاقة إلى آخر الفولدر",
        ["StatusMovedToFolderBottomPlural"] = "تم نقل العناصر إلى آخر الفولدر",
        ["StatusCopied"] = "تم النسخ",
        ["StatusPasted"] = "تم اللصق",
        ["StatusCopiedMultiple"] = "تم نسخ {0} عناصر معًا",
        ["StatusFolderEmpty"] = "الفولدر فارغ",
        ["StatusMovedToFolder"] = "تم النقل إلى {0}",
        ["StatusMovedToFolderPlural"] = "تم نقل {0} عناصر إلى {1}",
        ["StatusShortcutRemoved"] = "تمت إزالة اختصار البطاقة",
        ["StatusShortcutSaved"] = "تم حفظ اختصار لصق البطاقة",
        ["StatusShortcutConflict"] = "الاختصار مستخدم بالفعل؛ لم يتغير اختصار البطاقة",
        ["MenuRenameFolder"] = "إعادة تسمية الفولدر",
        ["MenuMoveFolderToTab"] = "نقل الفولدر إلى تبويب",
        ["MenuMoveFolderUp"] = "تحريك لأعلى ▲",
        ["MenuMoveFolderDown"] = "تحريك لأسفل ▼",
        ["MenuMoveFolderToTop"] = "نقل إلى أول القائمة ⤒",
        ["MenuMoveFolderToBottom"] = "نقل إلى آخر القائمة ⤓",
        ["MenuDeleteFolder"] = "حذف الفولدر…",
        ["DeleteFolderConfirm"] = "هل تريد حذف الفولدر «{0}»؟ ستبقى العناصر داخل التبويب.",
        ["DeleteTabConfirm"] = "هل تريد حذف التبويب «{0}»؟ سيتم نقل عناصره إلى «الكل».",
        ["TrayOpen"] = "فتح حافظة",
        ["TrayPauseResume"] = "إيقاف/استئناف الالتقاط",
        ["TrayExit"] = "خروج",
        ["SettingsTitle"] = "إعدادات حافظة",
        ["SettingsMaxEntries"] = "أقصى عدد للعناصر",
        ["SettingsCardDensity"] = "كثافة البطاقات",
        ["DensityCompact"] = "صغيرة",
        ["DensityMedium"] = "متوسطة",
        ["DensityLarge"] = "كبيرة",
        ["SettingsWindowPosition"] = "مكان ظهور النافذة",
        ["PositionBottomRight"] = "أسفل اليمين",
        ["PositionBottomLeft"] = "أسفل اليسار",
        ["PositionCenter"] = "منتصف الشاشة",
        ["SettingsTheme"] = "المظهر",
        ["ThemeDark"] = "داكن",
        ["ThemeLight"] = "فاتح",
        ["SettingsLanguage"] = "اللغة",
        ["LangEnglish"] = "الإنجليزية",
        ["LangArabic"] = "العربية",
        ["SettingsHotkey"] = "اختصار فتح البرنامج",
        ["SettingsHotkeyTooltip"] = "انقر هنا ثم اضغط الاختصار المطلوب",
        ["SettingsAnimations"] = "تشغيل حركة الظهور والاختفاء",
        ["SettingsStartup"] = "تشغيل حافظة مع ويندوز",
        ["SettingsBootCleanup"] = "تنظيف تبويب الكل بعد إعادة تشغيل ويندوز",
        ["SettingsBootCleanupTip"] = "تبويب الكل مؤقت، بينما التبويبات المخصصة محفوظة دائمًا.",
        ["SettingsBootCleanupHint"] = "يمسح كل ما يوجد في «الكل» عند بدء جلسة ويندوز جديدة، ويحفظ جميع عناصر التبويبات المخصصة كما هي.",
        ["SettingsExport"] = "تصدير نسخة احتياطية",
        ["SettingsImport"] = "استعادة نسخة",
        ["SettingsSave"] = "حفظ الإعدادات",
        ["DialogTabNameTitle"] = "اسم التبويب",
        ["DialogFolderNameTitle"] = "اسم الفولدر",
        ["DialogCardNameTitle"] = "اسم العنصر",
        ["DialogSave"] = "حفظ",
        ["DialogCancel"] = "إلغاء",
        ["DialogRemoveShortcut"] = "إزالة الاختصار",
        ["DialogHotkeyTitle"] = "اختصار اللصق",
        ["DialogHotkeyInstructions"] = "اضغط مفاتيح الاختصار على لوحة المفاتيح",
        ["ImagePreviewTitle"] = "معاينة الصورة",
        ["StatusFolderMoved"] = "تم نقل الفولدر ومعه {0} عنصر",
        ["StatusFolderDropHint"] = "أفلت الفولدر «{0}» لتغيير موضعه",
        ["StatusFolderContentsCopied"] = "تم نسخ محتويات {0}",
        ["StatusCopiedSelected"] = "تم نسخ العناصر المحددة",
        ["DeleteFolderPrompt"] = "نعم: احذف الفولدر وأخرج بطاقاته إلى التبويب.\nلا: احذف الفولدر وبطاقاته من هذا التبويب فقط.",
        ["DeleteFolderTitle"] = "حذف الفولدر",
        ["DeleteConfirmTitle"] = "تأكيد",
        ["DeleteCardsCountPrompt"] = "حذف {0} بطاقة من هذا التبويب؟",
        ["DeleteBatchConfirm"] = "سيتم حذف {0} عناصر من التبويب الحالي. يمكنك التراجع بعد الحذف.",
        ["DeleteBatchTitle"] = "تأكيد الحذف",
        ["TooltipUndoWithCount"] = "تراجع عن آخر حذف — {0} عملية متاحة",
        ["TooltipKeepOpenPinned"] = "مثبّتة: ستظل النافذة ظاهرة بعد اللصق",
        ["SettingsBackupFilter"] = "نسخة حافظة كاملة|*.hafiza",
        ["SettingsRestoreFilter"] = "نسخة حافظة كاملة|*.hafiza|نسخة قديمة|*.json",
        ["SettingsNoticeShortcutCaptured"] = "تم التقاط الاختصار. اضغط حفظ الإعدادات.",
        ["SettingsNoticeExportSuccess"] = "تم تصدير النسخة الاحتياطية.",
        ["SettingsNoticeExportFailed"] = "تعذّر تصدير النسخة. راجع زر عرض المشكلة.",
        ["SettingsNoticeImportFailed"] = "النسخة غير صالحة أو تعذّر استعادتها.",
        ["SettingsNoticeModifierOnly"] = "استخدم Ctrl أو Alt أو Shift فقط مع المفتاح.",
        ["MoreTabsTooltip"] = "المزيد من التبويبات",
    };

    public static string Get(string key)
    {
        var dict = IsArabic ? ArabicStrings : EnglishStrings;
        if (dict.TryGetValue(key, out var val)) return val;
        if (EnglishStrings.TryGetValue(key, out var fallback)) return fallback;
        return key;
    }

    public static string Get(string key, params object[] args)
    {
        var template = Get(key);
        try { return string.Format(template, args); }
        catch { return template; }
    }
}
